backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "property"
    label: "Properties"
    folder: "src/pages/property"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "property"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Images", name: "images", widget: "list", fields: [{label: ImagePath, name: imagePath, widget: image}, {label: Test, name: test, widget: hidden, required: false}]}

  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/pages/index.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
